apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      serviceAccount: admin
      containers:
        - name: telegraf
          image: ft-telegraf
          imagePullPolicy: Never
          ports:
            - containerPort: 8125
              name: http
