apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - port: 20
    protocol: TCP
    targetPort: 20
    name: port
  - port: 21
    protocol: TCP
    targetPort: 21
    name: ftps
  - port: 21000
    protocol: TCP
    targetPort: 21000
    name: ftps-passive-1
  - port: 21001
    protocol: TCP
    targetPort: 21001
    name: ftps-passive-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
        - name: ftps
          imagePullPolicy: Never
          image: ft-ftps
          ports:
          - containerPort: 20
          - containerPort: 21
          - containerPort: 21000
          - containerPort: 21001
          volumeMounts:
            - name: ftps-volume
              mountPath: /usr/share/ftps
      volumes:
        - name: ftps-volume
          persistentVolumeClaim:
            claimName: ftps-storage