apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: ftps-svc
  labels:
    app: ftps  
spec:
  type: LoadBalancer
  ports:
  - name: ftps-data
    port: 20
    targetPort: 20
    protocol: TCP
  - name: ftps-control
    port: 21
    targetPort: 21
    protocol: TCP
  - name: ftps-passive
    port: 21000
    protocol: TCP
    targetPort: 21000
  selector:
    app: ftps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
        - name: ftps
          image: ftps
          imagePullPolicy: Never
          ports:
          - containerPort: 20
            name: ftps-data 
          - containerPort: 21
            name: ftps-control
          - containerPort: 21000
            name: ftps-passive
          volumeMounts:
            - name: var-ftps
              mountPath: var/ftps
      volumes:
        - name: var-ftps
          persistentVolumeClaim:
            claimName: ftps-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-pvc
  labels:
    app: ftps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi