apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      serviceAccount: monitoring
      containers:
        - name: telegraf
          image: telegraf
          imagePullPolicy: Never
          ports:
            - containerPort: 8125
              name: http