# # config file version
apiVersion: 1

providers:
  - name: 'default'
    orgId: 1
    folder: ''
    folderUid: ''
    type: file
    options:
      path: /grafana-7.2.0/conf/provisioning/dashboards
